services:
  server:
    image: python:3.13-slim
    build:
      context: ./webapp-server
    env_file:
      - webapp-client/shared/.env
    volumes:
      - ./webapp-server/:/webapp-server
      - ./webapp-client/shared/:/config
    stop_signal: SIGINT
    depends_on:
      - mongodb
      - caddy
    networks:
      - internal

  client:
    image: node:22.9-slim
    build:
      context: ./webapp-client
    env_file:
      - webapp-client/shared/.env
    volumes:
      - ./webapp-client/:/webapp-client
    stop_signal: SIGTERM
    depends_on:
      - caddy
    networks:
      - internal

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    networks:
      - internal
    env_file:
      - webapp-client/shared/.env

  caddy:
    image: caddy:2.4.6
    env_file:
      - webapp-client/shared/.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    networks:
      - internal
      - external
    ports:
      - ${VITE_SERVER_PORT}:${VITE_SERVER_PORT}

volumes:
  mongodb:
    external: true
  caddy:
    external: true

networks:
  external:
    internal: false
  internal:
    external: false
