services:
  server:
    image: python:3.10-slim
    build:
      context: ./server
    env_file:
      - .env
    volumes:
      - ./server/:/server
    stop_signal: SIGINT
    depends_on:
      - mongodb
      - caddy
    networks:
      - internal

  client:
    image: node:22.9-slim
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - ./client/:/client
    stop_signal: SIGTERM
    depends_on:
      - caddy
    networks:
      - internal

  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb:/data/db
    networks:
      - internal
    env_file:
      - .env

  caddy:
    image: caddy:2.4.6
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    networks:
      - internal
      - external
    ports:
      # Only testing ports for now
      - 8080:8080
      - 8081:8081

volumes:
  mongodb:
    external: true
  caddy:
    external: true

networks:
  external:
    internal: false
  internal:
    external: false
